name: Build Armbian Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: clone repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: install requirements
        run: |
          task setup

      - name: copy userpatches
        run: |
          task copy
      
      - name: run build
        run: |
          task build

      - name: move image
        run: |
          task get-image

      